//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CrystalCPUID.rc
//
#define IDS_LH_K8_VOLTAGE               1
#define IDS_LH_COMMAND_LINE_JP          2
#define IDS_LH_COMMAND_LINE_EN          3
#define IDS_REAL_TIME_CLOCK_NO_LOAD_JP  4
#define IDS_REAL_TIME_CLOCK_NO_LOAD_EN  5
#define IDS_REAL_TIME_CLOCK_HELP_JP     6
#define IDS_REAL_TIME_CLOCK_HELP_EN     7
#define IDS_NOT_FOUND_SYS_INFO_DLL_JP   8
#define IDS_NOT_FOUND_SYS_INFO_DLL_EN   9
#define IDS_STOP_CRYSTAL_N_QUIET_JP     10
#define IDS_STOP_CRYSTAL_N_QUIET_EN     11
#define IDS_SET_NEW_FID_JP              12
#define IDS_SET_NEW_FID_EN              13
#define IDS_SET_NEW_VID_JP              14
#define IDS_SET_NEW_VID_EN              15
#define IDS_CAN_NOT_CREATE_SHORTCUT_JP  16
#define IDS_CAN_NOT_CREATE_SHORTCUT_EN  17
#define IDS_CREATE_SHORTCUT_JP          18
#define IDS_CREATE_SHORTCUT_EN          19
#define IDS_POP_SHOW_MAIN_DIALOG_JP     20
#define IDS_POP_SHOW_MAIN_DIALOG_EN     21
#define IDS_POP_HIDE_MAIN_DIALOG_JP     22
#define IDS_POP_HIDE_MAIN_DIALOG_EN     23
#define IDS_POP_EXIT_JP                 24
#define IDS_POP_EXIT_EN                 25
#define IDS_POP_ENABLE_CRYSTAL_N_QUIET_JP 26
#define IDS_POP_ENABLE_CRYSTAL_N_QUIET_EN 27
#define IDS_POP_DISABLE_CRYSTAL_N_QUIET_JP 28
#define IDS_POP_DISABLE_CRYSTAL_N_QUIET_EN 29
#define IDS_POP_SETTING_CRYSTAL_N_QUIET_JP 30
#define IDS_POP_SETTING_CRYSTAL_N_QUIET_EN 31
#define IDD_CRYSTALCPUID_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_RANKING                     131
#define IDB_BITMAP1                     139
#define IDR_MENU                        140
#define IDD_CUSTOMIZE                   141
#define IDD_FEATURE_DIALOG              142
#define IDD_CPUID_DIALOG                143
#define IDD_LOVE_HAMMER                 144
#define IDR_ACCELERATOR                 145
#define IDD_BIOS_INFO                   146
#define IDD_TRANSMETA_INFO              147
#define IDD_PROCESSOR_SERIAL            148
#define IDD_REAL_TIME_CLOCK             149
#define IDB_MATRIXLARGE                 150
#define IDB_MATRIXSMALL                 151
#define IDB_MATRIXTINY                  152
#define IDD_ABOUT                       153
#define IDD_LONG_HAUL                   154
#define IDD_QUERY_PERFORMANCE           155
#define IDD_CACHE_INFO                  156
#define IDD_CRYSTALCPUID_DIALOG_24      157
#define IDD_CRYSTALCPUID_DIALOG_POP     158
#define IDD_CRYSTALCPUID_DIALOG_26      159
#define IDD_DMI_INFO                    160
#define IDD_CHIPSET_INFO                161
#define IDD_PCI_INFO                    162
#define IDR_PCI_MENU                    163
#define IDR_9991                        166
#define IDD_DUMMY                       167
#define IDD_CRYSTAL_N_QUIET             168
#define IDR_TASKTRAY                    169
#define IDR_TASKTRAY_MAX                170
#define IDR_TASKTRAY_MID                171
#define IDR_TASKTRAY_MIN                173
#define IDD_MSR_EDIT                    174
#define IDD_MSR_WALKER                  175
#define IDD_SPEED_STEP                  176
#define IDD_CPU_MARK_2005               177
#define IDC_FEATURE_FLAG_STANDARD       1055
#define IDC_FEATURE_FLAG_EX             1056
#define IDC_FEATURE_FLAG_STANDARD_ECX   1057
#define IDC_FEATURE_FLAG_VIA            1058
#define IDC_FEATURE_FLAG_TRANSMETA      1059
#define IDC_FEATURE_FLAG_EX_ECX         1060
#define IDC_FEATURE_FLAG_POWER_MANAGEMENT 1061
#define IDC_CPU_OS                      1070
#define IDC_SELECT_FILE                 1071
#define IDC_CPU_CURRENT_DATE            1071
#define IDC_FEATURE_EX                  1072
#define IDC_CPU_SIGNATURE               1072
#define IDC_SELECT_FONT                 1072
#define IDC_SELECT_FONT_MAIN            1072
#define IDC_CPU_ARCHITECTURE            1073
#define IDC_SELECT_FONT_OTHER           1073
#define IDC_FILE_NAME                   1076
#define IDC_WINDOW_SIZE                 1077
#define IDC_IMAGE_SIZE                  1078
#define IDC_SELECT_COLOR                1079
#define IDC_CLEAR                       1080
#define IDC_TEXT_COLOR                  1081
#define IDC_CPU_PROCESS_RULE            1083
#define IDC_CPUID_LIST                  1085
#define IDC_SELECT_LCD_ON               1086
#define IDC_LCD_ON                      1087
#define IDC_SELECT_LCD_OFF              1088
#define IDC_LH_SET_FID                  1089
#define IDC_LCD_OFF                     1089
#define IDC_LH_SET_VID                  1090
#define IDC_SELECT_LCD_GRID             1090
#define IDC_LH_CURRENT_FID              1091
#define IDC_LCD_GRID                    1091
#define IDC_LH_STARTUP_FID              1092
#define IDC_LH_TYPE                     1092
#define IDC_LH_MAX_FID                  1093
#define IDC_LH_CURRENT_VID              1094
#define IDC_LH_STARTUP_VID              1095
#define IDC_LH_MAX_VID                  1096
#define IDC_CURRENT_CLOCK               1097
#define IDC_LH_SELECT_CPU               1097
#define IDC_LH_VOLTAGE_MESSAGE          1098
#define IDC_LH_VOLTAGE_DOWN             1099
#define IDC_LH_VOLTAGE_UP               1100
#define IDC_GRAY                        1100
#define IDC_BIOS_CAPTION                1103
#define IDC_BIOS_VERSION                1104
#define IDC_BIOS_DATE                   1105
#define IDC_SM_BIOS_CAPTION             1106
#define IDC_MOTHER_MANUFACTURER         1107
#define IDC_TM_CLOCK                    1107
#define IDC_MOTHER_PRODUCT              1108
#define IDC_TM_NOMINAL_CLOCK            1108
#define IDC_MOTHER_VERSION              1109
#define IDC_TM_NAME_STRING              1109
#define IDC_SYSTEM_MANUFACTURER         1110
#define IDC_TM_HARDWARE_VERSION         1110
#define IDC_FEATURE_NAME_1              1111
#define IDC_SYSTEM_MODEL                1111
#define IDC_TM_SOFTWARE_VERSION         1111
#define IDC_FEATURE_NAME_2              1112
#define IDC_BIOS_MANUFACTURER           1112
#define IDC_TM_CURRENT_VOLTAGE          1112
#define IDC_FEATURE_NAME_3              1113
#define IDC_TM_CURRENT_PERFORMANCE      1113
#define IDC_SM_BIOS_VERSION             1113
#define IDC_DMI_VERSION                 1113
#define IDC_FEATURE_NAME_4              1114
#define IDC_TM_CURRENT_GATE_DELAY       1114
#define IDC_FEATURE_NAME_5              1115
#define IDC_TM_REFRESH                  1115
#define IDC_FEATURE_NAME_6              1116
#define IDC_GET_WMI                     1116
#define IDC_FEATURE_NAME_7              1117
#define IDC_GET_WMI_MESSAGE             1117
#define IDC_FEATURE_NAME_8              1118
#define IDC_LH_CREATE_LINK              1118
#define IDC_FEATURE_NAME_9              1119
#define IDC_PROCESSOR_SERIAL            1119
#define IDC_FEATURE_NAME_10             1120
#define IDC_FEATURE_NAME_11             1121
#define IDC_LH_ENABLE_VOLTAGE           1121
#define IDC_FEATURE_NAME_12             1122
#define IDC_FEATURE_NAME_13             1123
#define IDC_LH_HELP                     1123
#define IDC_FEATURE_NAME_14             1124
#define IDC_RTC_CLOCK                   1124
#define IDC_FEATURE_NAME_15             1125
#define IDC_FEATURE_NAME_16             1126
#define IDC_SUB                         1126
#define IDC_FEATURE_NAME_17             1127
#define IDC_MAIN                        1127
#define IDC_LCD_SAMPLE                  1127
#define IDC_FEATURE_NAME_18             1128
#define IDC_FEATURE_NAME_19             1129
#define IDC_INTERVAL_TIME               1129
#define IDC_FEATURE_NAME_20             1130
#define IDC_RTC_NO_LOAD                 1130
#define IDC_FEATURE_NAME_21             1131
#define IDC_RTC_WITH_LOAD               1131
#define IDC_FEATURE_NAME_22             1132
#define IDC_RTC_NO_LOAD_MMT             1132
#define IDC_FEATURE_NAME_23             1133
#define IDC_RTC_HELP                    1133
#define IDC_FEATURE_NAME_24             1134
#define IDC_LCD_SAMPLE_1                1134
#define IDC_FEATURE_NAME_25             1135
#define IDC_LCD_SAMPLE_2                1135
#define IDC_FEATURE_NAME_26             1136
#define IDC_LCD_SAMPLE_3                1136
#define IDC_FEATURE_NAME_27             1137
#define IDC_LCD_SAMPLE_4                1137
#define IDC_FEATURE_NAME_28             1138
#define IDC_LCD_SAMPLE_5                1138
#define IDC_FEATURE_NAME_29             1139
#define IDC_LCD_SAMPLE_6                1139
#define IDC_FEATURE_NAME_30             1140
#define IDC_LCD_SAMPLE_7                1140
#define IDC_FEATURE_NAME_31             1141
#define IDC_LCD_SAMPLE_8                1141
#define IDC_FEATURE_NAME_32             1142
#define IDC_FEATURE_NAME_0              1142
#define IDC_LCD_SAMPLE_9                1142
#define IDC_LCD_SAMPLE_10               1143
#define IDC_RTC_TOPMOST                 1144
#define IDC_RTC_NO_LOAD_QPC             1145
#define IDC_LCD_SAMPLE_11               1146
#define IDC_LH_CONFIRMED_DIALOG         1147
#define IDC_RTC_NEW_TYPE                1147
#define IDC_QUERY_PERFORMANCE           1148
#define IDC_RTC_DIALOG_FONT             1148
#define IDC_CACHE_LIST                  1150
#define IDC_FONT_INFO                   1154
#define IDC_FONT_INFO_MAIN              1154
#define IDC_DMI_BIOS_VENDOR             1155
#define IDC_FONT_INFO_OTHER             1155
#define IDC_DMI_BIOS_VERSION            1156
#define IDC_DMI_BIOS_RELEASE_DATE       1157
#define IDC_DMI_BIOS_ROM_SIZE           1158
#define IDC_DMI_CPU_VERSION             1159
#define IDC_DMI_CPU_SOCKET              1160
#define IDC_DMI_CPU_CURRENT_CLOCK       1161
#define IDC_DMI_CPU_MANUFACTURER        1162
#define IDC_DMI_CPU_MAX_CLOCK           1163
#define IDC_PCI_LIST                    1163
#define IDC_DMI_CPU_EXTERNAL_CLOCK      1164
#define IDC_PCI_BUS                     1164
#define IDC_DMI_MOTHER_PRODUCT          1165
#define IDC_PCI_DEVICE                  1165
#define IDC_DMI_MOTHER_VERSION          1166
#define IDC_PCI_FUNCTION                1166
#define IDC_PCI_VENDOR_ID               1167
#define IDC_DMI_MOTHER_MANUFACTURER     1168
#define IDC_PCI__DEVICE_ID              1168
#define IDC_PCI__REVISION               1169
#define IDC_PCI_VENDOR_NAME             1170
#define IDC_PCI__DEVICE_NAME            1171
#define IDC_PCI__CLASS_ID               1172
#define IDC_PCI_SUB_SYSTEM_ID           1173
#define IDC_PCI_CLASS_NAME              1174
#define IDC_PCI_SUB_SYSTEM_NAME         1175
#define IDC_CHIPSET                     1176
#define IDC_NORTH_BRIDGE                1177
#define IDC_SOUTH_BRIDGE                1178
#define IDC_VIDEO_CHIP                  1179
#define IDC_NORTH_BRIDGE_ID             1180
#define IDC_LH_DESKTOP_VOLTAGE          1180
#define IDC_SOUTH_BRIDGE_ID             1181
#define IDC_CQ_MAX_FID                  1181
#define IDC_VIDEO_CHIP_ID               1182
#define IDC_CQ_MAX_VID                  1182
#define IDC_CQ_MIN_FID                  1183
#define IDC_CQ_MIN_VID                  1184
#define IDC_CQ_MID_FID                  1185
#define IDC_CQ_MID_VID                  1186
#define IDC_CQ_ENABLE_VOLTAGE           1187
#define IDC_CQ_MAX_INTERVAL_TIME        1188
#define IDC_CQ_MID_THRESHOLD_UP         1189
#define IDC_CQ_MAX_THRESHOLD_DOWN       1190
#define IDC_CQ_MID_INTERVAL_TIME        1191
#define IDC_CQ_MIN_INTERVAL_TIME        1192
#define IDC_CQ_MIN_THRESHOLD_UP         1193
#define IDC_CQ_MID_THRESHOLD_DOWN       1194
#define IDC_CQ_MODE_UP_TYPE_0           1196
#define IDC_CQ_MODE_UP_TYPE_1           1197
#define IDC_CQ_MODE_DOWN_TYPE_0         1200
#define IDC_CQ_MODE_DOWN_TYPE_1         1201
#define IDC_CQ_APPLY                    1202
#define IDC_CQ_COLORFUL_ICON            1208
#define IDC_CQ_EXIT_MODE                1209
#define IDC_CQ_VOLTAGE_MODE_DESKTOP     1210
#define IDC_CQ_WAIT_TIME                1210
#define IDC_FEATURE_INITIAL_1           1211
#define IDC_CQ_VOLTAGE_MODE_MOBILE      1211
#define IDC_BUTTON1                     1211
#define IDC_CQ_DUAL_WAIT_TIME           1211
#define IDC_MSR_SEARCH                  1211
#define IDC_MARK_32                     1211
#define IDC_TTI_MAX                     1211
#define IDC_DUMMY                       1211
#define IDC_FEATURE_INITIAL_2           1212
#define IDC_RDMSR_EDX                   1212
#define IDC_MSR_STOP                    1212
#define IDC_MARK_64                     1212
#define IDC_TTI_NORMAL                  1212
#define IDC_CQ_TRIGER_TYPE              1212
#define IDC_FEATURE_INITIAL_3           1213
#define IDC_RDMSR_EAX                   1213
#define IDC_TTI_MID                     1213
#define IDC_FEATURE_INITIAL_4           1214
#define IDC_WRMSR_EDX                   1214
#define IDC_TTI_MIN                     1214
#define IDC_FEATURE_INITIAL_5           1215
#define IDC_WRMSR_EAX                   1215
#define IDC_FEATURE_INITIAL_6           1216
#define IDC_ACCESS_MSR                  1216
#define IDC_FEATURE_INITIAL_7           1217
#define IDC_RDMSR                       1217
#define IDC_FEATURE_INITIAL_8           1218
#define IDC_WRMSR                       1218
#define IDC_CPU_MEASURE_MODE            1218
#define IDC_FEATURE_INITIAL_9           1219
#define IDC_MSR_START                   1219
#define IDC_FEATURE_INITIAL_10          1220
#define IDC_MSR_END                     1220
#define IDC_FEATURE_INITIAL_11          1221
#define IDC_FEATURE_INITIAL_12          1222
#define IDC_MSR_TIME                    1222
#define IDC_FEATURE_INITIAL_13          1223
#define IDC_MSR_RESULT                  1223
#define IDC_FEATURE_INITIAL_14          1224
#define IDC_FEATURE_INITIAL_15          1225
#define IDC_FEATURE_INITIAL_16          1226
#define IDC_FEATURE_INITIAL_17          1227
#define IDC_FEATURE_INITIAL_18          1228
#define IDC_FEATURE_INITIAL_19          1229
#define IDC_FEATURE_INITIAL_20          1230
#define IDC_FEATURE_INITIAL_21          1231
#define IDC_FEATURE_INITIAL_22          1232
#define IDC_FEATURE_INITIAL_23          1233
#define IDC_FEATURE_INITIAL_24          1234
#define IDC_FEATURE_INITIAL_25          1235
#define IDC_FEATURE_INITIAL_26          1236
#define IDC_FEATURE_INITIAL_27          1237
#define IDC_FEATURE_INITIAL_28          1238
#define IDC_FEATURE_INITIAL_29          1239
#define IDC_FEATURE_INITIAL_30          1240
#define IDC_FEATURE_INITIAL_31          1241
#define IDC_FEATURE_INITIAL_32          1242
#define IDC_FEATURE_INITIAL_0           1242
#define IDC_SS_SET_FID                  1244
#define IDC_SS_CURRENT_FID              1245
#define IDC_SS_MAX_FID                  1246
#define IDC_SS_SET_VID                  1247
#define IDC_SS_CURRENT_VID              1248
#define IDC_SS_MAX_VID                  1249
#define IDC_SS_CONFIRMED_DIALOG         1250
#define IDC_SS_CREATE_LINK              1251
#define IDC_SS_HELP                     1252
#define IDC_SS_ENABLE_VOLTAGE           1253
#define IDC_MSR_UPDATE_RESULT           1254
#define IDC_SS_MIN_VID                  1255
#define IDC_MARK_SCORE_32               1256
#define IDC_MARK_SCORE_64               1257
#define IDC_MARK_CPU_INFO               1259
#define IDC_MARK_CPU_CLOCK              1260
#define IDC_TTI_MAX_ICON                1260
#define IDC_TTI_NORMAL_ICON             1261
#define IDC_TTI_MID_ICON                1262
#define IDC_TTI_MIN_ICON                1263
#define IDC_TTI_DEFAULT                 1264
#define IDC_TTI_DISABLE                 1265
#define IDC_CPU_PROCESS_UNIT            1266
#define IDC_CPU_SYSTEM_BUS_HT           1267
#define IDC_FEATURE_SUPPORT_1           1311
#define IDC_FEATURE_SUPPORT_2           1312
#define IDC_FEATURE_SUPPORT_3           1313
#define IDC_FEATURE_SUPPORT_4           1314
#define IDC_FEATURE_SUPPORT_5           1315
#define IDC_FEATURE_SUPPORT_6           1316
#define IDC_FEATURE_SUPPORT_7           1317
#define IDC_FEATURE_SUPPORT_8           1318
#define IDC_FEATURE_SUPPORT_9           1319
#define IDC_FEATURE_SUPPORT_10          1320
#define IDC_FEATURE_SUPPORT_11          1321
#define IDC_FEATURE_SUPPORT_12          1322
#define IDC_FEATURE_SUPPORT_13          1323
#define IDC_FEATURE_SUPPORT_14          1324
#define IDC_FEATURE_SUPPORT_15          1325
#define IDC_FEATURE_SUPPORT_16          1326
#define IDC_FEATURE_SUPPORT_17          1327
#define IDC_FEATURE_SUPPORT_18          1328
#define IDC_FEATURE_SUPPORT_19          1329
#define IDC_FEATURE_SUPPORT_20          1330
#define IDC_FEATURE_SUPPORT_21          1331
#define IDC_FEATURE_SUPPORT_22          1332
#define IDC_FEATURE_SUPPORT_23          1333
#define IDC_FEATURE_SUPPORT_24          1334
#define IDC_FEATURE_SUPPORT_25          1335
#define IDC_FEATURE_SUPPORT_26          1336
#define IDC_FEATURE_SUPPORT_27          1337
#define IDC_FEATURE_SUPPORT_28          1338
#define IDC_FEATURE_SUPPORT_29          1339
#define IDC_FEATURE_SUPPORT_30          1340
#define IDC_FEATURE_SUPPORT_31          1341
#define IDC_FEATURE_SUPPORT_32          1342
#define IDC_FEATURE_SUPPORT_0           1342
#define IDC_CPU_CLOCK_ORI               1400
#define IDC_CPU_CPU_NAME                1401
#define IDC_CPU_NAME_STRING             1402
#define IDC_CPU_CLOCK                   1403
#define IDC_CPU_SYSTEM_CLOCK_ORI        1404
#define IDC_CPU_SYSTEM_CLOCK            1405
#define IDC_CPU_SYSTEM_BUS_ORI          1406
#define IDC_CPU_SYSTEM_BUS              1407
#define IDC_CPU_MULTIPLIER_ORI          1408
#define IDC_CPU_MULTIPLIER              1409
#define IDC_CPU_DATA_RATE               1410
#define IDC_CPU_OVER_CLOCK              1411
#define IDC_CPU_BRAND_ID                1412
#define IDC_CPU_APIC                    1413
#define IDC_CPU_VENDOR_STRING           1414
#define IDC_CPU_FAMILY                  1415
#define IDC_CPU_EX_FAMILY               1416
#define IDC_CPU_CACHE_L1_ITU            1417
#define IDC_CPU_L1_ITU_CACHE            1418
#define IDC_CPU_MODEL                   1419
#define IDC_CPU_EX_MODEL                1420
#define IDC_CPU_STEPPING                1421
#define IDC_CPU_EX_STEPPING             1422
#define IDC_CPU_FAMILY_EX               1423
#define IDC_CPU_MODEL_EX                1424
#define IDC_CPU_CACHE_L1_ITU2           1425
#define IDC_CPU_PLATFORM                1426
#define IDC_CPU_PLATFORM_ID             1427
#define IDC_CPU_CODE_NAME               1428
#define IDC_CPU_L1_D_CACHE              1429
#define IDC_CPU_L2_CACHE                1430
#define IDC_CPU_L3_CACHE                1431
#define IDC_CPU_L2_CACHE_SPEED          1432
#define IDC_CPU_L2_CACHE_SPEED_MHZ      1433
#define IDC_CPU_TYPE_ID                 1434
#define IDC_CPU_CRYSTAL_DEW_WORLD       1436
#define IDC_CPU_COPY                    1437
#define IDC_CPU_VERSION_INFO            1438
#define IDC_CPU_CACHE_L1_ITU_UNIT       1439
#define IDC_CPU_RANKING                 1440
#define IDC_CPU_PASSWORD                1441
#define IDC_CPU_MACHINE_NAME            1442
#define IDC_CPU_REFRESH                 1443
#define IDC_CPU_CPU_NUMBER              1444
#define IDC_CPU_CORE_NUMBER             1444
#define IDC_CPU_POST                    1445
#define IDC_CPU_USER_NAME               1446
#define IDC_CPU_MACHINE                 1447
#define IDC_CPU_MAIL                    1448
#define IDC_CPU_HOMEPAGE                1449
#define IDC_CPU_CPU                     1450
#define IDC_CPU_FIX                     1451
#define IDC_CPU_CORE_VOLTAGE            1452
#define IDC_CPU_IO_VOLTAGE              1453
#define IDC_CPU_MOTHER                  1454
#define IDC_CPU_CHIP_SET                1455
#define IDC_CPU_MEMORY                  1456
#define IDC_CPU_COOL                    1457
#define IDC_CPU_COMMENT                 1458
#define IDC_CPU_AFTER                   1459
#define IDC_CPU_AREA                    1460
#define IDC_CPU_HYPER_THREADING         1461
#define IDC_CPU_CPU_SELECT              1462
#define IDC_CPU_MICROCODE_ID            1463
#define IDC_CPU_MMX                     1464
#define IDC_CPU_SSE                     1465
#define IDC_CPU_SSE2                    1466
#define IDC_CPU_3DNOW                   1467
#define IDC_CPU_3DNOW_EX                1468
#define IDC_CPU_MMX_EX                  1469
#define IDC_CPU_HT                      1470
#define IDC_CPU_AMD_64                  1471
#define IDC_CPU_INTEL_64                1472
#define IDC_CPU_CACHE_LIST              1473
#define IDC_CPU_SPEED_STEP              1473
#define IDC_CPU_SSE3                    1474
#define IDC_CPU_TYPE                    1475
#define IDC_CPU_POWER_NOW               1476
#define IDC_CPU_LONG_HAUL               1477
#define IDC_CPU_LONG_RUN                1478
#define IDC_CPU_DUAL_CORE               1479
#define IDC_CPU_IA32E                   1480
#define IDC_CPU_NX                      1481
#define IDC_CPU_SSE4                    1482
#define IDC_CPU_SSE41                   1482
#define IDC_CPU_VT                      1483
#define IDC_CPU_AMD_V                   1484
#define IDC_CPU_SSSE3                   1485
#define IDC_CPU_SSE42                   1486
#define IDC_CPU_AVX                     1487
#define IDC_CPU_SSE4A                   1488
#define IDC_CPU_SSE5                    1489
#define IDS_CPU_NAME                    9999
#define IDM_EXIT                        32771
#define IDM_COPY                        32772
#define IDM_COPY_TEXT                   32772
#define IDM_JAPANESE                    32774
#define IDM_ENGLISH                     32775
#define IDM_SYS_INFO_TEXT               32776
#define IDM_CPU_INFO_TEXT               32776
#define IDM_CRYSTAL_CPUID_TEXT          32777
#define IDM_CPUID_INI                   32779
#define IDM_CRYSTAL_DEW_WORLD           32780
#define IDM_CUSTOMIZE                   32781
#define IDM_CPU_SUPPORT                 32782
#define IDM_REFRESH                     32783
#define IDM_LICENSE                     32784
#define IDM_FEATURE_FLAGS               32785
#define IDM_CPUID_DETAIL                32786
#define IDM_READ_ME                     32787
#define IDM_LOVE_HAMMER                 32788
#define IDM_QUERY_PERFORMANCE_FREQUENCY 32789
#define IDM_CPU_SUPPORT_CPU_LIST        32790
#define IDM_HIDE_ORIGINAL_CLOCK         32791
#define IDM_SAVE_IMAGE                  32792
#define IDM_SAVE_TEXT                   32793
#define IDM_PREVIEW_TEXT                32795
#define IDM_TRANSMETA_INFO              32796
#define IDM_QUICK_SAVE_IMAGE            32799
#define IDM_BIOS_INFO                   32800
#define IDM_PROCESSOR_SERIAL            32801
#define IDM_REAL_TIME_CLOCK             32802
#define IDM_ABOUT                       32803
#define IDM_LONG_HAUL                   32804
#define IDM_CACHE_INFO                  32805
#define IDM_REFRESH_WT                  32806
#define IDM_REFRESH_MMT                 32807
#define IDM_REFRESH_QPC                 32808
#define IDM_REFRESH_NOLOAD              32809
#define IDM_DMI_INFO                    32810
#define IDM_CHIPSET_INFO                32812
#define IDM_HIDE_DATE                   32815
#define IDM_ENABLE_CRYSTAL_N_QUIET      32816
#define IDM_CRYSTAL_N_QUIET             32817
#define IDM_CRYSTAL_CPUID_INI           32818
#define IDM_PCI_INFO                    32819
#define IDM_MSR_EDIT                    32821
#define IDM_MSR_WALKER                  32822
#define IDM_SPEED_STEP                  32823
#define IDM_CPU_MARK_2005               32824
#define IDM_CRYSTAL_CPUID_HISTORY_TEXT  32825
#define IDM_CPU_INFO_HISTORY_TEXT       32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1268
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
